# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/zack/528CA51E8CA4FE1B/Users/zacks/Documents/UB/Senior/Fall 2017/CSE490/smallpond_temp/Smallpond/uart/uart.srcs/sources_1/ip/clk_div/clk_div.xci
# IP: The module: 'clk_div' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/zack/528CA51E8CA4FE1B/Users/zacks/Documents/UB/Senior/Fall 2017/CSE490/smallpond_temp/Smallpond/uart/uart.srcs/sources_1/ip/clk_div/clk_div_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_div'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /media/zack/528CA51E8CA4FE1B/Users/zacks/Documents/UB/Senior/Fall 2017/CSE490/smallpond_temp/Smallpond/uart/uart.srcs/sources_1/ip/clk_div/clk_div.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_div'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /media/zack/528CA51E8CA4FE1B/Users/zacks/Documents/UB/Senior/Fall 2017/CSE490/smallpond_temp/Smallpond/uart/uart.srcs/sources_1/ip/clk_div/clk_div_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_div'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /media/zack/528CA51E8CA4FE1B/Users/zacks/Documents/UB/Senior/Fall 2017/CSE490/smallpond_temp/Smallpond/uart/uart.srcs/sources_1/ip/clk_div/clk_div.xci
# IP: The module: 'clk_div' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/zack/528CA51E8CA4FE1B/Users/zacks/Documents/UB/Senior/Fall 2017/CSE490/smallpond_temp/Smallpond/uart/uart.srcs/sources_1/ip/clk_div/clk_div_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_div'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /media/zack/528CA51E8CA4FE1B/Users/zacks/Documents/UB/Senior/Fall 2017/CSE490/smallpond_temp/Smallpond/uart/uart.srcs/sources_1/ip/clk_div/clk_div.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_div'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /media/zack/528CA51E8CA4FE1B/Users/zacks/Documents/UB/Senior/Fall 2017/CSE490/smallpond_temp/Smallpond/uart/uart.srcs/sources_1/ip/clk_div/clk_div_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_div'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
