# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/zack/528CA51E8CA4FE1B/Users/zacks/Documents/UB/Senior/Fall 2017/CSE490/smallpond/Smallpond/smallpond_top/smallpond_top.srcs/sources_1/ip/memory/memory.xci
# IP: The module: 'memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/zack/528CA51E8CA4FE1B/Users/zacks/Documents/UB/Senior/Fall 2017/CSE490/smallpond/Smallpond/smallpond_top/smallpond_top.srcs/sources_1/ip/memory/memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'memory'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /media/zack/528CA51E8CA4FE1B/Users/zacks/Documents/UB/Senior/Fall 2017/CSE490/smallpond/Smallpond/smallpond_top/smallpond_top.srcs/sources_1/ip/memory/memory.xci
# IP: The module: 'memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/zack/528CA51E8CA4FE1B/Users/zacks/Documents/UB/Senior/Fall 2017/CSE490/smallpond/Smallpond/smallpond_top/smallpond_top.srcs/sources_1/ip/memory/memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'memory'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
